FROM tensorflow/serving

# Copy the model directory into the Docker image
COPY serving_models/food_pred /models/food_pred

# Specify the model name environment variable
ENV MODEL_NAME food_pred_model

# Expose the TensorFlow Serving REST API port
EXPOSE 8501

# Run TensorFlow Model Server
ENTRYPOINT ["/usr/bin/tensorflow_model_server", "--port=8500", "--rest_api_port=8501", "--model_base_path=/models/food_pred", "--model_name=food_pred"]
