FROM tensorflow/serving

COPY serving_models/food_pred /models/food_pred

ENV MODEL_NAME food_pred

EXPOSE 8501

ENTRYPOINT ["/usr/bin/tensorflow_model_server", "--port=8500", "--rest_api_port=8501", "--model_base_path=/models/food_pred", "--model_name=food_pred"]
