name: Keep Services Alive

on:
  schedule:
    # Runs every 1 minute
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Navigate to the correct directory if needed
    - name: Navigate to script directory
      working-directory: cron-job  # Ensure this is correct
      run: pwd

    - name: Install dependencies
      run: npm install
      working-directory: cron-job  # Ensure this is correct

    - name: Run Keep Alive Script
      run: node index.js
      working-directory: cron-job  # Ensure this is correct
